# Generated by Django 4.0.3 on 2022-04-05 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ygt', '0003_alter_exercise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='added_by',
            field=models.ManyToManyField(related_name='added', to=settings.AUTH_USER_MODEL),
        ),
    ]
