# Generated by Django 4.0.3 on 2022-04-05 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ygt', '0005_remove_exercise_added_by_exercise_exercise_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_list',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerc9se',
            field=models.ManyToManyField(related_name='added', to=settings.AUTH_USER_MODEL),
        ),
    ]
