# Generated by Django 4.0.3 on 2022-04-05 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ygt', '0006_remove_exercise_exercise_list_exercise_exerc9se'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exerc9se',
            new_name='added_by',
        ),
    ]
