# Generated by Django 4.0.3 on 2022-04-05 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ygt', '0007_rename_exerc9se_exercise_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='categories', to='ygt.exercise'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='added_by',
            field=models.ManyToManyField(blank=True, related_name='added', to=settings.AUTH_USER_MODEL),
        ),
    ]
